# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables for the PostgreSQL user and password
ENV POSTGRES_USER=docker
ENV POSTGRES_PASSWORD=password

# Optionally, set the database name
ENV POSTGRES_DB=mydatabase